services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: "America/New York"
      FTLCONF_webserver_api_password: "password"
      FTLCONF_LOCAL_IPV4: 192.168.99.3
      FTLCONF_dns_listeningMode: "all"
      PIHOLE_DNS_: 172.21.200.3#5353 # forward to unbound
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole.toml:/etc/pihole/pihole.toml:rw
    networks:
      pihole_network:
        ipv4_address: 172.21.200.2
    restart: unless-stopped
    depends_on:
      - unbound
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    volumes:
      - ./unbound:/opt/unbound/etc/unbound:rw
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:rw
      - ./root.hints:/opt/unbound/etc/unbound/root.hints:rw
    networks:
      pihole_network:
        ipv4_address: 172.21.200.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  pihole_network:
    driver: bridge
    name: "pihole_network"
    ipam:
      config:
        - subnet: 172.21.200.0/24
          gateway: 172.21.200.1
          ip_range: 172.21.200.0/24
